### ISSUE TITLE
update a file inside the asar? instead of unpacking editing and repacking it again.

### ISSUE THREAD

**Issue by TomieAi** [craftersmine/Asar.NET#5]

**Comment by craftersmine** [comment]
You will still need to unpack and repack files at the end of edited file, because if file become bigger, it will overlap file at the end, and make file that located in the end of edited file corrupted

**Comment by craftersmine** [comment]
ASAR is still an archive, and no archive format can edit file on the fly without repacking the whole archive

**Comment by TomieAi** [comment]
how about repacking the unpacked one?

**Comment by craftersmine** [comment]
You need so separatelly add root entries, for example, if your archive has 3 files and one directory in root, you need to use AddFile() three times and AddDirectory() one time. This is from the [project wiki](https://github.com/craftersmine/Asar.NET/wiki/Creating-new-ASAR-archives)
> You need to keep in mind, that all Add methods are relative to archive root, so method AddFile will add file at the root of an archive, if you want to create a directory structure, use AddDirectory to add a directory of files to the archive. AddDirectory will add a provided directory as a directory in an archive root, so directory like C:\some_dir\dir will become asar_arc.asar\dir. All subdirectories and subfiles will be also added to this directory.

**Comment by craftersmine** [comment]
This code
![image](https://github.com/craftersmine/Asar.NET/assets/11241645/df20a5a4-2fb9-43f3-9458-6813b5aa7234)
Will result in
![image](https://github.com/craftersmine/Asar.NET/assets/11241645/be8563b7-39e8-4fcf-b6bc-b83d896cd3da)
